export const srhKnowledgeBase = [
  {
    id: 'emergency',
    keywords: ['emergency', 'crisis', 'pain', 'severe pain', 'bleeding', 'heavy bleeding', 'hurt', 'suicide', 'self-harm', 'die', 'kill', 'abuse', 'danger', 'dangerous', 'raped', 'assault', 'assaulted', 'force', 'forced', 'rape', 'sexual assault', 'domestic violence', 'help me'],
    response: "🚨 **Your Safety is the Absolute Priority** 🚨\n\nIf you are in immediate physical danger, experiencing severe pain, heavy bleeding, or feeling like you might harm yourself, please seek immediate emergency care:\n- **Emergency Hotline**: Call your local emergency services (e.g., 911 / 112 / local health emergency number).\n- **Youth Support Line**: Contact a local helpline or visit our **Emergency Help** tab for direct links to hotlines.\n- **Sexual Assault Support**: If you have experienced sexual assault or rape:\n  - Try to get to a safe place immediately.\n  - Go to a local hospital or clinic as soon as possible. They can provide **emergency contraception** (to prevent pregnancy) and **PEP** (to prevent HIV) within 72 hours.\n  - Try not to wash, bathe, or change clothes before going, as this helps preserve forensic evidence if you choose to report it.\n  - Remember: **It is never your fault.** Support and counseling are available."
  },
  {
    id: 'menstruation',
    keywords: ['period', 'periods', 'menstruation', 'menstrual', 'flow', 'cycle', 'pms', 'pad', 'pads', 'tampon', 'tampons', 'cup', 'menstrual cup', 'liner', 'liners', 'cramp', 'cramps', 'menstruating', 'ovulation phase', 'luteal', 'follicular'],
    response: "🌸 **Menstrual Health & Period Guidance** 🌸\n\nPeriods are a completely natural and healthy sign that your reproductive system is developing. Here is what you need to know:\n\n1. **What is a Normal Cycle?**\n   - A typical cycle lasts **21 to 35 days** (measured from the first day of one period to the first day of the next).\n   - Bleeding usually lasts **3 to 7 days**.\n   - In the first few years, cycles can be highly irregular—that is completely normal!\n\n2. **The 4 Phases of the Menstrual Cycle:**\n   - **Menstruation Phase**: The shedding of the uterine lining (your period). Estrogen and progesterone levels are low.\n   - **Follicular Phase**: The brain signals the ovaries to prepare an egg. The lining of the uterus thickens.\n   - **Ovulation Phase**: The ovary releases a mature egg (typically around day 14 of a 28-day cycle). This is your **most fertile window**.\n   - **Luteal Phase**: The body prepares for a potential pregnancy. If it doesn't happen, hormone levels drop, leading back to menstruation.\n\n3. **Managing Cramps (Dysmenorrhea):**\n   - Place a **warm compress** or hot water bottle on your lower abdomen.\n   - Stay well-hydrated and do light stretching or gentle walking.\n   - Warm herbal teas (like chamomile or ginger) can help soothe tension.\n\n4. **Menstrual Products:**\n   - **Disposable**: Sanitary pads, pantyliners, and tampons.\n   - **Reusable**: Menstrual cups, period underwear, and washable cloth pads.\n   - *Note: Always wash your hands before and after changing products. Change pads/tampons every 4–6 hours to maintain hygiene and prevent infections.* \n\n5. **When to Consult a Doctor:**\n   - If your pain is severe enough to stop you from going to school or doing daily activities.\n   - If you need to change your pad or tampon every hour because it is completely soaked.\n   - If your period suddenly stops for more than 3 months."
  },
  {
    id: 'hormonal_conditions',
    keywords: ['pcos', 'polycystic ovary syndrome', 'endometriosis', 'irregular periods pain', 'severe period pain', 'painful periods doctor', 'excess body hair', 'ovarian cysts', 'cysts ovaries', 'hormonal imbalance'],
    response: "🎗️ **Understanding PCOS & Endometriosis** 🎗️\n\nMany young women suffer from underlying hormonal and reproductive conditions that go undiagnosed. Knowing the signs helps you seek clinical care early:\n\n1. **PCOS (Polycystic Ovary Syndrome):**\n   - **What it is**: A common hormonal disorder causing enlarged ovaries with small cysts.\n   - **Symptoms**: Very irregular or missed periods, heavy bleeding, excess facial/body hair (hirsutism), severe acne, and weight gain.\n   - **Management**: Managed effectively with lifestyle adjustments, diet support, or hormonal therapy (like birth control pills) prescribed by a doctor.\n\n2. **Endometriosis:**\n   - **What it is**: A condition where tissue similar to the uterus lining grows outside the uterus (on ovaries, fallopian tubes, etc.).\n   - **Symptoms**: **Severe, debilitating period cramps** that don't respond to standard painkillers, pain during intercourse, heavy flows, and chronic pelvic pain.\n   - **Management**: Requires professional diagnosis. Treatments include pain management, hormonal therapies, or minor procedures.\n\n*If you experience debilitating pain or highly irregular periods, do not just suffer through it—book a confidential video chat with our clinicians in the Consult tab.*"
  },
  {
    id: 'pmdd',
    keywords: ['pmdd', 'severe pms', 'suicidal before period', 'depressed before period', 'angry before period', 'premenstrual dysphoric disorder'],
    response: "🧠 **PMDD (Premenstrual Dysphoric Disorder)** 🧠\n\nPMDD is a much more severe form of PMS that significantly impacts mental health in the week or two before your period.\n\n**Symptoms:**\n- Severe depression, anxiety, or feelings of hopelessness before your period.\n- Extreme mood swings, anger, or irritability that affects your relationships.\n- Physical symptoms like bloating, breast tenderness, and extreme fatigue.\n- Symptoms magically disappear a few days after your period starts.\n\n**What to do:**\n- This is a real medical condition caused by your brain's severe sensitivity to normal hormone fluctuations.\n- **Do not suffer in silence.** Doctors can treat PMDD effectively with certain birth control pills (like Yaz) or SSRI antidepressants taken specifically during that part of your cycle."
  },
  {
    id: 'groin_health',
    keywords: ['lump groin', 'swollen lymph nodes groin', 'pain sex', 'painful sex', 'groin pain', 'blister groin', 'sores genitals', 'groin rash', 'groin itching', 'genital growth', 'wart groin', 'painful intercourse', 'dyspareunia'],
    response: "🔍 **Groin Health & Signs of Infection** 🔍\n\nYour groin and genital areas can exhibit signs that indicate a medical issue. Monitor your body for these warning flags:\n\n- **Swollen Lymph Nodes in the Groin**: Small, pea-sized, tender bumps in the crease between your thigh and lower abdomen. They swell when your body is fighting off a localized infection (like an STI or skin cut).\n- **Genital Sores or Blisters**: Painful blisters or open sores around the vulva, vagina, penis, or anus can indicate a viral infection (like Herpes) or bacterial infection (like Syphilis). These require direct medical treatment.\n- **Pain During Intercourse (Dyspareunia)**: Pain during or after sex is **not** something you should ignore. It can be caused by vaginal dryness, infections, endometriosis, or pelvic inflammatory disease.\n- **Genital Growths or Warts**: Small, flesh-colored bumps that resemble tiny cauliflowers can indicate HPV (Genital Warts).\n\n*If you experience any groin pain, swollen nodes, or sores, schedule a highly confidential consult under the Consult tab.*"
  },
  {
    id: 'male_groin_issues',
    keywords: ['jock itch', 'tinea cruris', 'itchy groin boys', 'rash groin balls', 'phimosis', 'tight foreskin', 'cant pull back foreskin', 'painful foreskin', 'groin fungus', 'testicular pain', 'lump on testicle', 'varicocele', 'epididymitis'],
    response: "🩹 **Male Groin Conditions: Complete Guide** 🩹\n\nYoung men can encounter specific groin conditions that cause discomfort or worry:\n\n1. **Jock Itch (Tinea Cruris):** Fungal infection causing an itchy, red, ring-shaped rash on the inner thighs. Keep dry and use over-the-counter anti-fungal cream.\n\n2. **Phimosis (Tight Foreskin):** When foreskin is too tight to pull back. Never force it back! Use safe stretching techniques or steroid creams prescribed by a doctor.\n\n3. **Testicular Torsion:** Sudden, severe testicular pain. The spermatic cord twists, cutting off blood supply. **This is a medical emergency. Go to the hospital immediately.** You only have a few hours to save the testicle.\n\n4. **Epididymitis:** Inflammation of the tube at the back of the testicle. Causes dull, heavy pain and swelling. Often caused by an STI like chlamydia or gonorrhea. Needs antibiotics.\n\n5. **Varicocele:** Enlarged veins in the scrotum (feels like a \"bag of worms\"). Mostly harmless but can cause dull aching or affect fertility later in life.\n\n6. **Testicular Lumps:** Any hard, painless lump on the testicle itself must be checked by a doctor to rule out testicular cancer, which is highly curable if caught early."
  },
  {
    id: 'sti_overview',
    keywords: ['sti', 'std', 'stis', 'stds', 'test', 'testing', 'swab', 'blood test', 'exposure', 'unprotected', 'transmission', 'transmit', 'checkup'],
    response: "🩺 **STI Prevention & Testing** 🩺\n\nSexually Transmitted Infections (STIs) are passed through sexual contact (vaginal, anal, or oral). They are common, highly preventable, and mostly treatable.\n\n**The Golden Rule of STIs:** Most people with an STI have **ZERO SYMPTOMS (asymptomatic)**. The only way to know is to get tested.\n\n**Common Symptoms (when they do occur):**\n- Unusual discharge (fluid) from vagina or penis.\n- Burning when urinating.\n- Sores, blisters, bumps, or rashes on genitals.\n- Unusual itching or unpleasant odor.\n\n**How to protect yourself:**\n- Use condoms or dental dams every time you have sex.\n- Get tested before having sex with a new partner.\n- Talk openly with your partners about testing."
  },
  {
    id: 'sti_chlamydia_gonorrhea',
    keywords: ['chlamydia', 'gonorrhea', 'clap', 'drip', 'burning pee', 'yellow discharge penis', 'green discharge vagina', 'pelvic inflammatory disease', 'pid'],
    response: "🦠 **Chlamydia & Gonorrhea** 🦠\n\nThese are two of the most common bacterial STIs. They are easily cured with antibiotics but can cause severe damage if left untreated.\n\n**Symptoms:**\n- Often **none** (especially in women).\n- Burning during urination.\n- Abnormal yellow/green discharge from penis or vagina.\n- Pain or swelling in testicles.\n- Bleeding between periods.\n\n**Dangers if left untreated:**\nIn women, untreated chlamydia or gonorrhea can spread to the uterus and fallopian tubes, causing **Pelvic Inflammatory Disease (PID)**, which can lead to chronic pain and permanent infertility.\n\n**Treatment:** A simple course of prescription antibiotics cures them completely. Do not have sex until both you and your partner have finished treatment."
  },
  {
    id: 'sti_syphilis',
    keywords: ['syphilis', 'chancre', 'painless sore', 'rash hands feet', 'rash palms soles', 'neurosyphilis'],
    response: "🦠 **Syphilis** 🦠\n\nSyphilis is a serious bacterial STI that develops in stages. It is highly curable with penicillin in its early stages but can cause permanent organ damage, blindness, or death if ignored for years.\n\n**The Stages:**\n1. **Primary Stage:** A single, painless, firm, round sore (called a chancre) appears where the bacteria entered (genitals, anus, or mouth). It heals on its own in 3-6 weeks, *but the infection is still in your body.*\n2. **Secondary Stage:** A non-itchy skin rash appears, often on the palms of hands and soles of feet. You may also have fever, swollen lymph glands, and fatigue.\n3. **Latent Stage:** No visible symptoms. The bacteria remain hidden in your body for years.\n4. **Tertiary Stage:** Severe damage to brain, nerves, eyes, heart, blood vessels, liver, bones, and joints.\n\n**Takeaway:** If you ever see a strange, painless sore on your genitals, see a doctor immediately."
  },
  {
    id: 'sti_herpes',
    keywords: ['herpes', 'hsv', 'hsv1', 'hsv2', 'cold sores', 'fever blisters', 'genital blisters', 'incurable sti', 'tingling genitals'],
    response: "🦠 **Herpes (HSV-1 & HSV-2)** 🦠\n\nHerpes is a very common viral STI. It is not curable, but it is highly manageable.\n\n- **HSV-1:** Typically causes oral herpes (cold sores/fever blisters around the mouth). However, through oral sex, it can easily be spread to the genitals.\n- **HSV-2:** Typically causes genital herpes.\n\n**Symptoms:**\n- Often preceded by tingling, itching, or burning in the genital area.\n- Followed by an outbreak of painful, fluid-filled blisters that burst and leave shallow ulcers.\n- First outbreak is usually the worst; subsequent outbreaks become milder and less frequent over time.\n\n**Management:**\n- There is no cure, but antiviral medications (like Valacyclovir) can speed up healing, reduce outbreaks, and drastically lower the chance of passing it to a partner.\n- You are highly contagious during an active outbreak. Avoid sexual contact from the moment you feel tingling until the sores have completely healed and new skin has formed."
  },
  {
    id: 'sti_hpv',
    keywords: ['hpv', 'human papillomavirus', 'warts', 'genital warts', 'cervical cancer', 'pap smear', 'gardasil', 'hpv vaccine'],
    response: "🦠 **HPV (Human Papillomavirus)** 🦠\n\nHPV is the most common STI in the world. Almost every sexually active person will get it at some point. There are many strains.\n\n- **Low-Risk Strains:** Can cause genital warts (small, cauliflower-like bumps). These are annoying but harmless.\n- **High-Risk Strains:** Can cause cell changes that lead to cancer over many years, primarily **cervical cancer**, but also anal, throat, and penile cancers.\n\n**Prevention & Care:**\n- **The HPV Vaccine (Gardasil):** Highly effective at preventing the most dangerous strains of HPV. Usually given around ages 11-12, but catch-up vaccines are available for older youths.\n- **Pap Smears / HPV Tests:** People with a cervix should start getting regular Pap smears at age 21. This test catches abnormal cell changes *before* they become cancer, allowing for easy removal.\n- There is no treatment for the virus itself, but your immune system usually clears it within 1-2 years."
  },
  {
    id: 'hiv_aids_prep',
    keywords: ['hiv', 'aids', 'prep', 'pep', 'undetectable', 'u=u', 'hiv positive', 'antiretroviral'],
    response: "🩸 **HIV, AIDS, PrEP & PEP** 🩸\n\nHIV is a virus that attacks the immune system. If untreated, it leads to AIDS. However, modern medicine has completely changed HIV from a fatal disease to a manageable chronic condition.\n\n**Prevention:**\n- **PrEP (Pre-Exposure Prophylaxis):** A daily pill (like Truvada or Descovy) taken by HIV-negative people. It is 99% effective at preventing HIV from sex.\n- **PEP (Post-Exposure Prophylaxis):** Emergency medicine taken **within 72 hours** of a potential HIV exposure (e.g., condom break, sexual assault) to prevent the virus from taking hold.\n\n**Treatment & U=U:**\n- People living with HIV take Antiretroviral Therapy (ART). \n- ART lowers the amount of virus in the blood to undetectable levels.\n- **U=U (Undetectable = Untransmissible):** A person with an undetectable viral load **cannot** pass HIV to their sexual partners. They live long, perfectly healthy lives."
  },
  {
    id: 'sti_trich_mycoplasma',
    keywords: ['trichomoniasis', 'trich', 'mycoplasma genitalium', 'mgen', 'ureaplasma', 'frothy discharge', 'smelly green discharge'],
    response: "🦠 **Trichomoniasis & Mycoplasma Genitalium (MGen)** 🦠\n\nBeyond Chlamydia and Gonorrhea, these are two other common but less-talked-about STIs.\n\n**Trichomoniasis (Trich):**\n- Caused by a tiny parasite.\n- Symptoms (mainly in women): Copious, frothy, yellow-green vaginal discharge with a strong, foul odor. Pain during sex or urination.\n- Men rarely have symptoms.\n- Easily cured with a specific antibiotic (Metronidazole or Tinidazole).\n\n**Mycoplasma Genitalium (MGen):**\n- A bacterial STI that acts similarly to Chlamydia.\n- Can cause persistent urethritis (burning pee) in men and cervicitis/PID in women.\n- It is known for being resistant to standard antibiotics like Azithromycin, so doctors may need to prescribe Moxifloxacin to cure it."
  },
  {
    id: 'vaginitis_comparison_chart',
    keywords: ['yeast vs bv', 'discharge comparison', 'discharge table', 'discharge chart', 'infection table', 'infection chart', 'vaginosis vs candidiasis', 'yeast infection', 'bacterial vaginosis', 'bv'],
    response: "📊 **Vaginal Discharge & Infection Reference Table** 📊\n\nHere is a simple reference comparing normal discharge with common infections:\n\n| Condition | Typical Discharge | Key Symptoms | Common Smell | Treatment |\n| :--- | :--- | :--- | :--- | :--- |\n| **Normal Discharge** | Clear, stretchy, or thin white | None | No smell or slightly sweet | None needed |\n| **Yeast Infection** | Thick, white, clumpy (cottage cheese-like) | Intense vaginal itching, burning, redness | None | Over-the-counter anti-fungal |\n| **Bacterial Vaginosis (BV)** | Thin, watery, greyish-white | Mild itching, burning, redness | **Strong fishy odor** (noticeable after sex) | Prescription antibiotics |\n| **Trichomoniasis (STI)** | Frothy, yellow or green | Pain during sex, painful urination, itching | Foul or musty odor | Prescription antibiotics |\n| **Gonorrhea / Chlamydia** | Cloudy, yellow, or increased volume | Pain, bleeding after sex, or **zero symptoms** | Foul odor | Prescription antibiotics |\n\n*This table is for educational reference. If you suspect an infection, consult our clinical team for a confirmed prescription.*"
  },
  {
    id: 'discharge_decipher',
    keywords: ['white discharge', 'grey discharge', 'yellow discharge', 'green discharge', 'discharge color', 'clear discharge', 'stretchy discharge', 'discharge texture', 'slimy discharge', 'creamy discharge', 'brown discharge', 'spotting', 'discharge smell'],
    response: "💧 **Deciphering Vaginal Discharge** 💧\n\nVaginal discharge is a completely normal fluid produced by glands in the vagina and cervix to carry away old cells and keep the canal clean. Color and texture change throughout your cycle:\n\n- **Clear & Stretchy (Like raw egg whites)**: Normal. Occurs during your **fertile window (ovulation)**. It helps sperm travel.\n- **White & Creamy**: Normal. Occurs at the beginning or end of your cycle. As long as there is no itching, burning, or bad odor, it is healthy.\n- **Thick, White & Clumpy (Like cottage cheese)**: Indicates a **Yeast Infection** (candidiasis), especially if accompanied by intense itching and redness. Readily treatable with anti-fungal cream.\n- **Thin, Grey/White with Fishy Odor**: Sign of **Bacterial Vaginosis (BV)**, an imbalance of bacteria. Requires antibiotics from a doctor.\n- **Yellow or Green**: Often bubbly, thick, or has a strong bad smell. This is a common sign of an **STI** (like chlamydia, gonorrhea, or trichomoniasis). You should get tested and see a doctor.\n- **Brown or Bloody**: If it happens right after your period, it is just old blood clearing out. If it is random spotting between periods, it is best to discuss it with a doctor."
  },
  {
    id: 'contraception_pills_combined_mini',
    keywords: ['birth control pill', 'the pill', 'combined pill', 'mini pill', 'progestin only pill', 'missed pill', 'forgot pill', 'pill side effects', 'estrogen'],
    response: "💊 **Birth Control Pills: Combined vs. Mini-Pill** 💊\n\nThe pill is a daily medication taken to prevent pregnancy. There are two main types:\n\n1. **Combined Oral Contraceptive (COC):**\n   - Contains both Estrogen and Progestin.\n   - Works by stopping ovulation (no egg released).\n   - Great for regulating periods, reducing cramps, and clearing acne.\n   - **Rules**: Should be taken around the same time daily. If you miss one, take it as soon as you remember, even if it means taking two in one day.\n\n2. **The Mini-Pill (Progestin-Only Pill or POP):**\n   - Contains only Progestin (no estrogen). Safe for those who can't take estrogen (e.g., history of blood clots, breastfeeding).\n   - Works by thickening cervical mucus to block sperm.\n   - **Rules**: Must be taken at the **EXACT SAME TIME** every day. Being even 3 hours late can make it ineffective for the next 48 hours.\n\n**Common Side Effects**: Nausea, breast tenderness, spotting between periods during the first 3 months. If severe, talk to your doctor about switching brands."
  },
  {
    id: 'contraception_iud',
    keywords: ['iud', 'intrauterine device', 'mirena', 'kyleena', 'paragard', 'copper iud', 'hormonal iud', 'coil', 'iud insertion', 'iud pain'],
    response: "⚓ **IUDs (Intrauterine Devices): Hormonal vs. Copper** ⚓\n\nAn IUD is a tiny T-shaped device inserted into your uterus by a doctor. It is one of the most effective, \"set it and forget it\" methods available (>99% effective).\n\n1. **Hormonal IUD (e.g., Mirena, Kyleena, Liletta):**\n   - Releases a small amount of progestin locally into the uterus.\n   - Lasts 3 to 8 years depending on the brand.\n   - **Huge Perk**: Often makes periods much lighter, shorter, and less painful. Some people stop getting periods entirely (which is safe!).\n\n2. **Copper IUD (e.g., Paragard):**\n   - Completely hormone-free! Wrapped in copper wire, which is naturally toxic to sperm.\n   - Lasts up to 10 or 12 years.\n   - **Drawback**: Can make periods heavier and crampier, especially in the first 6 months.\n\n**Insertion:** It only takes a few minutes but can cause sharp cramping. Taking ibuprofen beforehand helps. Once inserted, you shouldn't feel it at all."
  },
  {
    id: 'contraception_implant_shot_patch_ring',
    keywords: ['nexplanon', 'implant', 'arm implant', 'depo', 'depo provera', 'the shot', 'injection', 'birth control patch', 'nuvaring', 'vaginal ring'],
    response: "💉 **Implants, Shots, Patches, & Rings** 💉\n\nIf you don't want to remember a daily pill, here are excellent alternatives:\n\n1. **The Implant (Nexplanon):**\n   - A tiny, flexible rod inserted under the skin of your upper arm.\n   - Lasts for 3 to 5 years. Over 99% effective.\n   - Can cause irregular spotting or lighter periods.\n\n2. **The Shot (Depo-Provera):**\n   - An injection of progestin given every 3 months (12 weeks).\n   - Highly effective. Many users stop having periods while on it.\n   - **Drawback**: Can cause temporary weight gain in some people, and it may take up to a year for fertility to return after stopping.\n\n3. **The Patch (Xulane/Twirla):**\n   - A sticky patch you wear on your skin (belly, arm, back). You change it once a week for 3 weeks, then go patch-free for 1 week to have a period.\n\n4. **The Ring (NuvaRing/Annovera):**\n   - A flexible ring you insert into your vagina yourself. You leave it in for 3 weeks, take it out for 1 week (to have a period), and put a new one in. You usually can't feel it during sex."
  },
  {
    id: 'emergency_contraception_deep_dive',
    keywords: ['plan b', 'morning after pill', 'emergency contraception', 'ella', 'copper iud emergency', 'plan b weight limit', 'levonorgestrel'],
    response: "🚨 **Emergency Contraception: A Deep Dive** 🚨\n\nIf your primary birth control failed (e.g., condom broke, missed pills) or you had unprotected sex, you have up to 5 days to prevent pregnancy, but act fast!\n\n1. **Levonorgestrel Pills (Plan B, Take Action, My Way):**\n   - **Window**: Best within 72 hours (3 days).\n   - **How it works**: It delays your ovary from releasing an egg (ovulation). If you have *already* ovulated, Plan B will NOT work.\n   - **Weight Limit**: Efficacy decreases significantly for people weighing over 165 lbs (75 kg).\n\n2. **Ulipristal Acetate (Ella):**\n   - **Window**: Highly effective up to 120 hours (5 days) after sex.\n   - **Perk**: Works closer to the time of ovulation than Plan B, and is more effective for people with higher BMIs (up to 195 lbs).\n   - **Requirement**: Usually requires a prescription.\n\n3. **The Copper IUD:**\n   - **Window**: Can be inserted up to 5 days after unprotected sex.\n   - **The Ultimate Emergency Contraceptive**: It is 99.9% effective regardless of your weight or where you are in your cycle. Bonus: it provides hormone-free birth control for the next 10+ years!"
  },
  {
    id: 'barrier_methods_spermicide',
    keywords: ['condom', 'condoms', 'male condom', 'female condom', 'internal condom', 'diaphragm', 'cervical cap', 'sponge', 'spermicide', 'lube', 'lubricant'],
    response: "🛡️ **Barrier Methods & Lubricants** 🛡️\n\nBarrier methods block sperm from entering the uterus. Condoms are the ONLY method that also protect against STIs.\n\n1. **External Condoms (Male Condoms):**\n   - Typically made of latex, polyurethane, or polyisoprene (for latex allergies).\n   - **Rule**: NEVER use oil-based lubricants (like Vaseline, baby oil, or coconut oil) with latex condoms—they will break within seconds! Only use water-based or silicone-based lube.\n\n2. **Internal Condoms (Female Condoms):**\n   - A nitrile pouch inserted into the vagina (or anus) before sex. Has a flexible ring at each end. Great for giving the receiving partner control over protection.\n\n3. **Diaphragms, Caps, & Sponges:**\n   - Silicone cups or foam sponges inserted deep into the vagina to cover the cervix.\n   - Must be used with **spermicide** (a chemical that kills sperm) to be effective.\n   - Must be left in for at least 6 hours after sex.\n\n4. **Spermicide (Nonoxynol-9):**\n   - Comes in gels, foams, or films. \n   - **Warning**: Using spermicide alone is not very effective. Also, frequent use can irritate the vaginal lining, actually *increasing* your risk of getting HIV/STIs if exposed."
  },
  {
    id: 'fertility_awareness_withdrawal',
    keywords: ['pull out method', 'withdrawal', 'pulling out', 'fertility awareness', 'fam', 'rhythm method', 'tracking ovulation', 'safe days', 'basal body temperature'],
    response: "📅 **Natural Methods: Withdrawal & Fertility Awareness** 📅\n\nThese methods do not use hormones or devices, but they require strict discipline and have higher failure rates.\n\n1. **The Withdrawal Method (Pulling Out):**\n   - Pulling the penis out of the vagina before ejaculation.\n   - **Warning**: Pre-ejaculate (pre-cum) can contain active sperm. Even if pulled out in time, pregnancy can occur. It offers ZERO protection against STIs.\n   - Typical use effectiveness is only about 78%. Not recommended for youth trying to avoid pregnancy.\n\n2. **Fertility Awareness Methods (FAM):**\n   - Involves tracking your menstrual cycle every single day to identify your fertile window (the ~6 days a month you can get pregnant), and abstaining from sex or using condoms during that time.\n   - Requires tracking basal body temperature (with a special thermometer before you get out of bed), cervical mucus consistency, and calendar dates.\n   - Very difficult to do correctly if your periods are irregular, if you are stressed, or if your sleep schedule varies. Not recommended as a primary method for youth."
  },
  {
    id: 'sexual_dysfunction_conditions',
    keywords: ['vaginismus', 'cant penetrate', 'sex hurts too much', 'erectile dysfunction', 'cant get hard', 'ed', 'premature ejaculation', 'finishing too fast', 'anorgasmia', 'cant cum', 'cant orgasm', 'low libido', 'no sex drive'],
    response: "🧠 **Understanding Sexual Dysfunction** 🧠\n\nStruggling with sexual function is incredibly common and usually highly treatable. It can stem from physical issues, anxiety, trauma, or stress.\n\n1. **Vaginismus (For people with vaginas):**\n   - **What it is**: Involuntary tightening or spasms of the pelvic floor muscles, making penetration (tampons, fingers, penises, medical exams) painful or impossible.\n   - **Treatment**: Pelvic floor physical therapy, dilator therapy, and psychological counseling. It is highly curable!\n\n2. **Anorgasmia (Difficulty reaching orgasm):**\n   - Many people, especially women, do not orgasm from penetration alone. Clitoral stimulation is necessary for most. Stress, antidepressants, or lack of knowledge about one's body can also play a huge role.\n\n3. **Erectile Dysfunction (ED):**\n   - Difficulty getting or keeping an erection. In youth, this is almost always caused by **performance anxiety**, stress, or overconsumption of porn (porn-induced ED), rather than physical disease.\n\n4. **Premature Ejaculation (PE):**\n   - Ejaculating sooner than desired. Very common in young men due to excitement and anxiety. Can be managed with techniques like the \"stop-start\" method, desensitizing condoms, or counseling.\n\nNever feel ashamed—sex therapists and doctors handle these issues every single day."
  },
  {
    id: 'anatomy_female_deep',
    keywords: ['vulva', 'vagina', 'clitoris', 'labia', 'cervix', 'uterus', 'fallopian tubes', 'ovaries', 'hymen', 'g-spot', 'skenes gland', 'bartholins gland', 'female anatomy'],
    response: "🌺 **Detailed Female Reproductive Anatomy** 🌺\n\nKnowing the correct terms empowers you to understand your body and speak to doctors accurately:\n\n- **Vulva**: The external genitalia. Includes the mons pubis, labia majora (outer lips), labia minora (inner lips), clitoris, and the openings to the urethra and vagina.\n- **Clitoris**: A highly sensitive organ located at the top of the vulva, solely dedicated to sexual pleasure. What you see is just the tip (glans); the rest of it extends deep inside the body like a wishbone!\n- **Vagina**: The internal, muscular canal that connects the vulva to the cervix. It is where menstrual blood leaves the body and where penetration occurs.\n- **Cervix**: The lower, narrow part of the uterus that opens into the vagina. It produces mucus and dilates (opens) during childbirth.\n- **Uterus (Womb)**: A pear-shaped, muscular organ where a fetus grows. Its lining (endometrium) thickens and sheds each month (your period).\n- **Ovaries**: Two small glands that store and release eggs (ovulation) and produce estrogen and progesterone.\n- **Fallopian Tubes**: Tubes connecting the ovaries to the uterus. Fertilization of an egg by a sperm usually happens here.\n- **The Hymen Myth**: The hymen is a thin, stretchy fringe of tissue at the vaginal opening. It naturally wears away from physical activity, tampons, or sex. **It does not \"break\" or pop, and an intact hymen is not a reliable indicator of virginity.**"
  },
  {
    id: 'anatomy_male_deep',
    keywords: ['penis', 'testicles', 'balls', 'scrotum', 'prostate', 'epididymis', 'vas deferens', 'seminal vesicles', 'cowpers gland', 'foreskin', 'glans', 'male anatomy', 'urethra'],
    response: "🍆 **Detailed Male Reproductive Anatomy** 🍆\n\nUnderstanding male anatomy helps with hygiene, sexual health, and identifying problems early:\n\n- **Penis**: The external organ used for urination and sexual intercourse. Made of spongy tissue that fills with blood during an erection. The head is called the **glans**, which is highly sensitive.\n- **Foreskin**: A retractable sleeve of skin covering the glans. If a person is circumcised, this has been surgically removed.\n- **Scrotum**: The sac of skin holding the testicles. It regulates their temperature (sperm must be kept slightly cooler than body temperature, which is why the scrotum shrinks in the cold and hangs lower in the heat).\n- **Testicles (Testes)**: Two oval organs inside the scrotum that produce sperm and testosterone.\n- **Epididymis**: A tightly coiled tube at the back of each testicle where sperm mature and are stored.\n- **Vas Deferens**: The muscular tubes that transport mature sperm from the epididymis to the urethra in preparation for ejaculation. (This is what is cut during a vasectomy).\n- **Prostate Gland & Seminal Vesicles**: Internal glands that produce the fluids that mix with sperm to create semen, providing nourishment and mobility for the sperm.\n- **Cowper's Gland**: Produces pre-ejaculate (pre-cum) to neutralize acidity in the urethra before ejaculation. Pre-cum can contain active sperm!"
  },
  {
    id: 'safe_sex_acts',
    keywords: ['oral sex safe', 'anal sex safe', 'dental dam', 'swallowing cum', 'hiv from oral', 'sti from oral', 'lube for anal', 'safe anal', 'safe oral', 'rimming', 'blowjob safe', 'eating out safe'],
    response: "🛡️ **Safe Sex Practices by Activity** 🛡️\n\nSTIs can be transmitted through any mucous membrane contact (genitals, mouth, anus). Here is how to stay safe during different activities:\n\n1. **Oral Sex (Mouth-to-Penis / Mouth-to-Vulva / Mouth-to-Anus):**\n   - **Risks**: High risk for Herpes (HSV-1/2), Gonorrhea, Syphilis, and HPV in the throat. Extremely low risk for HIV.\n   - **Protection**: Use a flavored, non-lubricated condom on a penis. Use a **dental dam** (or a cut-open condom) over a vulva or anus.\n\n2. **Anal Sex (Penis-to-Anus):**\n   - **Risks**: The lining of the anus is very thin and tears easily, making it the **highest-risk sexual activity for HIV transmission**, as well as other STIs.\n   - **Protection**: Use a condom every single time. \n   - **Lube is Mandatory**: The anus does not self-lubricate. Use generous amounts of water-based or silicone-based lube to prevent painful tearing and condom breakage.\n   - **Hygiene**: Never go from anal penetration straight to vaginal penetration without changing the condom or washing thoroughly, to prevent severe vaginal or bladder infections.\n\n3. **Vaginal Sex (Penis-to-Vagina):**\n   - **Risks**: High risk for pregnancy and all STIs.\n   - **Protection**: Use condoms combined with a highly effective birth control method (double protection)."
  },
  {
    id: 'pregnancy_trimesters_complications',
    keywords: ['trimesters', 'ectopic pregnancy', 'preeclampsia', 'gestational diabetes', 'postpartum depression', 'ppd', 'morning sickness', 'pregnancy complications', 'when to go to hospital pregnant'],
    response: "🤰 **Pregnancy Stages & Serious Complications** 🤰\n\nPregnancy is a massive physical undertaking. It is divided into three Trimesters (about 13 weeks each). \n\n**Common Complications to Watch For:**\n\n1. **Ectopic Pregnancy (Medical Emergency):**\n   - The fertilized egg implants *outside* the uterus, usually in a fallopian tube. It cannot survive, and if it ruptures the tube, it causes fatal internal bleeding.\n   - **Symptoms**: Severe, sharp pain on one side of the lower abdomen/pelvis, vaginal bleeding, extreme dizziness.\n\n2. **Preeclampsia:**\n   - A dangerous spike in blood pressure after 20 weeks of pregnancy. Can lead to organ damage or fatal seizures.\n   - **Symptoms**: Severe headaches, vision changes (seeing spots), sudden swelling of face and hands.\n\n3. **Gestational Diabetes:**\n   - High blood sugar that develops during pregnancy. Requires diet management or insulin to protect the baby's growth.\n\n4. **Postpartum Depression (PPD):**\n   - Severe, persistent depression, anxiety, or feelings of detachment from the baby after birth. This is an illness, not a failure as a mother. Requires immediate psychiatric and medical support."
  },
  {
    id: 'gender_identity_transitioning',
    keywords: ['hrt', 'hormone replacement therapy', 'testosterone', 'estrogen', 'top surgery', 'bottom surgery', 'binding', 'binder safe', 'tucking safe', 'transgender healthcare', 'gender dysphoria', 'social transition'],
    response: "🏳️‍⚧️ **Gender Identity & Transitioning** 🏳️‍⚧️\n\nTransitioning is the process of aligning one's life and body with their gender identity. It looks different for everyone.\n\n1. **Social Transition:**\n   - Changing your name, pronouns, clothing, and hairstyle. This requires no medical intervention but is deeply affirming.\n\n2. **Medical Transition (HRT & Surgery):**\n   - **HRT (Hormone Replacement Therapy)**: Taking Testosterone (for trans men/transmasculine) or Estrogen & Testosterone Blockers (for trans women/transfeminine) to induce physical changes like voice deepening, facial hair, breast growth, and fat redistribution.\n   - **Surgeries**: Top surgery (chest masculinization or breast augmentation) and Bottom surgery (genital reconstruction).\n\n3. **Safe Binding & Tucking:**\n   - **Binding** (flattening the chest): Use a properly sized commercial binder. **NEVER use Ace bandages or duct tape**, as they restrict breathing and can permanently damage ribs and lung capacity. Never bind for more than 8 hours, and never sleep or heavily exercise in a binder.\n   - **Tucking** (flattening the genital bulge): Use specialized tucking underwear (gaffs) or medical tape. Avoid cutting off circulation. Take breaks to avoid pain or infection."
  },
  {
    id: 'consent_boundaries',
    keywords: ['consent', 'boundaries', 'forced', 'pressure', 'pressured', 'saying no', 'no means no', 'relationships', 'toxic', 'red flags', 'healthy relationship', 'abuse', 'gaslighting', 'manipulation', 'coercion', 'stealthing'],
    response: "🤝 **Consent, Boundaries & Healthy Relationships** 🤝\n\nHealthy relationships are built on mutual respect, trust, and clear communication. Understanding consent is the foundation of any intimate interaction.\n\n1. **What is Consent? (F.R.I.E.S.)**\n   - **Freely given**: It is not consent if it's pressured, manipulated, or under the influence of drugs/alcohol.\n   - **Reversible**: Anyone can change their mind at any time, even after they've already said yes or started the activity.\n   - **Informed**: You can only consent to what you know. (e.g., if you agree to sex with a condom, and the partner removes it without asking, that is a violation of consent called 'stealthing').\n   - **Enthusiastic**: It should be a clear \"Yes!\" not a \"maybe\" or \"I guess so.\"\n   - **Specific**: Saying yes to one thing (like kissing) doesn't mean saying yes to something else.\n\n2. **Red Flags in a Relationship:**\n   - Extreme jealousy or trying to isolate you from friends/family.\n   - Checking your phone constantly or demanding passwords.\n   - Pressuring you to send intimate photos or do sexual acts you aren't comfortable with.\n   - Gaslighting (making you doubt your own memories or feelings).\n\nIf you ever feel unsafe, pressured, or uncomfortable, **you have the right to leave and seek help.**"
  },
  {
    id: 'lgbtq_sexual_health',
    keywords: ['gay', 'lesbian', 'bisexual', 'trans', 'transgender', 'queer', 'lgbt', 'lgbtq', 'lgbtq+', 'same sex', 'pronouns', 'gender identity', 'sexual orientation', 'coming out', 'transitioning', 'pansexual', 'asexual'],
    response: "🌈 **LGBTQ+ Sexual Health & Identity** 🌈\n\nYour sexual orientation and gender identity are valid, normal, and a beautiful part of who you are. Health care should always be inclusive and respectful of your identity.\n\n1. **Sexual Orientation vs. Gender Identity:**\n   - **Sexual Orientation** is who you are attracted to (e.g., gay, lesbian, bisexual, straight, pansexual, asexual).\n   - **Gender Identity** is your internal sense of your own gender (e.g., male, female, transgender, non-binary, genderqueer).\n\n2. **LGBTQ+ Sexual Health Considerations:**\n   - **STIs don't discriminate**: STIs can be transmitted during any type of sexual contact (oral, anal, or vaginal/front-hole) regardless of the genders of the partners. \n   - **Protection**: Use condoms, dental dams, and finger cots to reduce STI transmission during diverse sexual acts.\n   - **PrEP & PEP**: Highly recommended preventative tools against HIV for populations at higher risk.\n   - **Pregnancy**: Transgender men and non-binary people with a uterus/ovaries can still get pregnant, even if they are on testosterone. Contraception is still needed if having sex that can lead to pregnancy.\n\n3. **Finding Support:**\n   - Coming out or questioning your identity can be confusing or stressful. You are not alone. Our platform provides a safe, non-judgmental space to talk to affirming clinicians."
  },
  {
    id: 'pregnancy_abortion',
    keywords: ['pregnant', 'pregnancy', 'abortion', 'miscarriage', 'positive test', 'pregnancy test', 'missed period', 'pregnant now what', 'options', 'terminate', 'keep baby', 'mifepristone', 'misoprostol', 'abortion pill'],
    response: "🤰 **Pregnancy, Options, and Care** 🤰\n\nIf you suspect you might be pregnant, the first step is to take a deep breath. You have time to figure this out, and there are professionals who can help you.\n\n1. **Taking a Pregnancy Test:**\n   - Home pregnancy tests are very accurate if taken **after** your missed period. If you take it too early, you might get a false negative. If your period is very late, take a test.\n\n2. **If the Test is Positive:**\n   You have options, and the decision is entirely yours. Depending on your local laws, your options generally include:\n   - **Parenting**: Choosing to give birth and raise the child. Prenatal care should begin immediately.\n   - **Adoption**: Choosing to give birth and legally placing the child with another family or individual.\n   - **Abortion**: Choosing to terminate the pregnancy. A **medical abortion** uses pills (mifepristone and misoprostol) and is safely done at home up to 10-11 weeks. A **surgical abortion** is an in-clinic procedure. Both are highly safe medical procedures when done legally and by professionals.\n\n3. **Miscarriage:**\n   - A spontaneous loss of a pregnancy, usually in the first 20 weeks. It is very common and is **never your fault**. If you experience heavy bleeding, severe cramps, and tissue passing, see a doctor immediately."
  },
  {
    id: 'masturbation_pleasure',
    keywords: ['masturbation', 'masturbate', 'touching myself', 'pleasure', 'orgasm', 'is masturbation normal', 'is masturbation healthy', 'vibrator', 'toys', 'rubbing clit', 'jerking off', 'fingering'],
    response: "✨ **Masturbation & Exploring Your Body** ✨\n\nLet's talk about it openly: **Masturbation is a completely normal, healthy, and safe way to explore your body and experience pleasure.**\n\nHere are the facts:\n- **It's Universal**: People of all genders, ages, and relationship statuses masturbate.\n- **Health Benefits**: It relieves stress, helps you sleep better, releases \"feel-good\" endorphins, and can even help relieve menstrual cramps.\n- **No Harm**: It does not cause blindness, stunt growth, cause infertility, or cause acne. Those are old myths!\n- **Learning About Yourself**: It is the best way to learn what feels good for your body, which helps you communicate your needs better if you eventually have a sexual partner.\n- **When is it an issue?**: Masturbation is only an issue if it starts to interfere with your daily life, school, work, or social relationships, or if you do it in public spaces.\n\nAs long as you are in private and maintaining basic hygiene, it is a perfectly healthy part of human sexuality."
  },
  {
    id: 'puberty_body_changes',
    keywords: ['puberty', 'body changes', 'breasts growing', 'voice deepening', 'pubic hair', 'acne', 'pimples', 'sweat', 'body odor', 'wet dreams', 'nocturnal emissions', 'growing up', 'armpit hair', 'growth spurt'],
    response: "🌱 **Puberty & Body Changes** 🌱\n\nPuberty is the time in your life when your body goes through changes to become an adult. It usually happens between ages 8 and 14, but everyone's timeline is different!\n\n**Common Changes for Everyone:**\n- **Growth Spurts**: You will grow taller and gain weight. Your body shape will change.\n- **Skin and Hair**: You might get acne or pimples due to hormones. Hair will grow under your arms and around your genitals (pubic hair).\n- **Sweat**: Your sweat glands become more active, which can cause body odor. Daily showers and using deodorant help!\n\n**Common Changes for People with Vulvas/Ovaries:**\n- Breast development begins.\n- Hips may widen.\n- Vaginal discharge starts, followed eventually by the first period (menarche).\n\n**Common Changes for People with Penises/Testicles:**\n- Testicles and penis grow larger.\n- Voice deepens (voice \"cracking\" is normal).\n- May experience \"wet dreams\" (nocturnal emissions), which is when you ejaculate semen while sleeping. This is completely normal and you can't control it.\n- Facial and chest hair may start growing.\n\nRemember, your body is doing exactly what it's supposed to do. If you feel awkward or self-conscious, know that everyone goes through it!"
  },
  {
    id: 'hygiene',
    keywords: ['wash', 'hygiene', 'clean', 'cleaning', 'smell down there', 'douche', 'douching', 'soap on vagina', 'smelly discharge', 'washing genitals', 'smegma', 'uncircumcised clean'],
    response: "🧼 **Intimate Hygiene Best Practices** 🧼\n\nKeeping your genital area clean is important, but doing it wrong can actually cause infections!\n\n**For People with Vulvas/Vaginas:**\n- **The vagina is self-cleaning!** You do not need to wash inside it.\n- **NEVER douche.** Douching flushes out the good, protective bacteria and increases the risk of yeast infections, BV, and STIs.\n- **How to wash**: Wash only the *outside* (the vulva) with warm water. If you must use soap, use a mild, unscented one. Avoid perfumed soaps, bubble baths, and scented wipes.\n- **Wipe front to back**: Always wipe from front to back after using the toilet to prevent bacteria from your anus from entering your vagina or urethra.\n\n**For People with Penises:**\n- Wash the penis and scrotum with warm water and mild soap.\n- **If uncircumcised**: Gently pull back the foreskin and wash underneath to clean away smegma (a natural buildup of dead skin cells and oils). Rinse well and gently pull the foreskin back over the head.\n\n**General Tips:**\n- Wear breathable, cotton underwear.\n- Change out of sweaty workout clothes or wet swimsuits quickly."
  },
  {
    id: 'uti_bladder_infection',
    keywords: ['uti', 'urinary tract infection', 'bladder infection', 'burns to pee', 'peeing constantly', 'pain peeing', 'blood in urine', 'cranberry juice uti'],
    response: "🚽 **Urinary Tract Infections (UTIs)** 🚽\n\nA UTI is an infection in any part of your urinary system (kidneys, ureters, bladder, and urethra). They are very common, especially for people with vulvas.\n\n**Symptoms:**\n- A strong, persistent urge to urinate.\n- A burning sensation when urinating.\n- Passing frequent, small amounts of urine.\n- Urine that appears cloudy, red, bright pink, or cola-colored (sign of blood).\n- Pelvic pain.\n\n**Prevention Tips:**\n- Drink plenty of water daily.\n- **Pee after sex!** This helps flush out bacteria that may have been pushed into the urethra during intercourse.\n- Wipe from front to back after using the bathroom.\n- Avoid irritating feminine products like deodorant sprays or powders in the genital area.\n\n**Treatment:**\nIf you think you have a UTI, you need to see a doctor. They are easily treated with a short course of antibiotics. Untreated UTIs can spread to the kidneys and become very serious. Cranberry juice will not cure an existing UTI."
  },
  {
    id: 'breast_health',
    keywords: ['breast', 'breasts', 'boobs', 'lump in breast', 'breast pain', 'bra', 'bras', 'breast development', 'nipple', 'nipples', 'nipple discharge', 'breast self exam'],
    response: "🍈 **Breast Health & Development** 🍈\n\nBreasts come in all shapes, sizes, and colors. It is completely normal for one breast to be slightly larger than the other, or for nipples to point in different directions!\n\n**Breast Development:**\n- Usually begins between ages 8 and 13. \n- They can feel tender or sore while they are growing. This is normal!\n\n**Breast Pain & Lumps:**\n- It is very common for breasts to feel swollen, lumpy, or painful right before your period due to hormone changes.\n- **Fibroadenomas**: These are harmless, solid, movable lumps very common in teenagers and young women. \n- **When to see a doctor**: If you find a hard lump that doesn't move, a lump that doesn't go away after your period, noticeable changes in breast shape/skin texture (like orange peel skin), or bloody/unusual discharge from the nipple.\n\n**Bras:**\n- Wearing a bra is entirely a personal choice! If you do wear one, make sure it fits well. A poorly fitting bra (especially underwire) can cause back pain, shoulder pain, and even breast tissue bruising."
  },
  {
    id: 'toxic_shock_syndrome',
    keywords: ['tss', 'toxic shock syndrome', 'left tampon in', 'forgot tampon', 'sleeping with tampon', 'fever during period', 'rash from tampon'],
    response: "⚠️ **Toxic Shock Syndrome (TSS) & Tampon Safety** ⚠️\n\nTSS is a rare but life-threatening complication caused by bacterial toxins. While it can happen to anyone with an open wound, it is most commonly associated with using super-absorbent tampons or leaving a tampon/menstrual cup in for too long.\n\n**Prevention:**\n- **Change tampons every 4 to 8 hours max.**\n- Never leave a tampon in for more than 8 hours (use a pad overnight while sleeping).\n- Always use the lowest absorbency tampon necessary for your flow.\n- Remove menstrual cups at least every 12 hours to wash them.\n\n**Symptoms of TSS (Medical Emergency!):**\n- A sudden high fever.\n- Low blood pressure (feeling extremely dizzy or fainting).\n- Vomiting or diarrhea.\n- A rash that looks like a sunburn, especially on your palms and soles.\n\n*If you have a tampon in and experience these symptoms, remove the tampon immediately and go to the emergency room!*"
  },
  {
    id: 'vaginal_flora_ph',
    keywords: ['ph balance', 'vaginal ph', 'vaginal flora', 'probiotics for vagina', 'yoni pearls', 'yoni wash', 'boric acid', 'vagina health'],
    response: "⚖️ **Vaginal pH & Microbiome Health** ⚖️\n\nYour vagina has its own delicate ecosystem (the vaginal flora), primarily made of good bacteria called *Lactobacilli*. These keep the vagina slightly acidic (pH 3.8 to 4.5), which naturally kills off bad bacteria and yeast.\n\n**How to Protect Your pH Balance:**\n- **Avoid Douching**: This is the #1 way to destroy your healthy bacteria.\n- **Beware of \"Yoni\" Products**: So-called detox pearls, scented washes, and steams are a scam and are highly dangerous. The vagina does not need to be \"detoxed\" or scented.\n- **Let it Breathe**: Sleep without underwear occasionally and wear breathable cotton during the day.\n- **Antibiotics**: Taking antibiotics for a completely different issue (like strep throat) can kill the good bacteria in your vagina, leading to a yeast infection. Eating yogurt with live cultures or taking a probiotic can help replenish the good bacteria.\n- **Boric Acid**: Sometimes recommended by doctors to treat stubborn BV or yeast infections by restoring acidity, but *never* use it without consulting a clinician first."
  },
  {
    id: 'first_gyno_visit',
    keywords: ['pap smear', 'pelvic exam', 'first gynecologist', 'gyno visit', 'obgyn', 'does a pap smear hurt', 'what happens at the gyno', 'speculum'],
    response: "🩺 **What to Expect: Your First Gynecologist Visit** 🩺\n\nGoing to the gynecologist (OB/GYN) for the first time can feel intimidating, but knowing what to expect makes it much easier! You usually have your first visit between ages 13 and 15 for a basic health chat, and your first pelvic exam/Pap smear at age 21 (unless you have painful problems earlier).\n\n**What Happens:**\n1. **The Chat**: The doctor will ask about your period (when it started, how heavy it is, cramps), if you are sexually active, and if you need birth control or STI testing.\n2. **The Breast Exam**: The doctor feels your breasts to check for unusual lumps. It takes about 30 seconds.\n3. **The Pelvic Exam (If needed)**:\n   - You lie back and place your feet in footrests (stirrups).\n   - The doctor looks at your external vulva.\n   - They gently insert a specialized tool called a **speculum** into the vagina. It feels like pressure but shouldn't hurt.\n   - **The Pap Smear**: Using a tiny soft brush, they swab the cervix to collect cells and test for HPV/cancer. It takes 5 seconds. You might feel a quick pinch or cramp.\n\n*You always have the right to ask the doctor to stop, to ask for a smaller speculum, or to have a parent/friend in the room with you!*"
  },
  {
    id: 'menarche_first_period',
    keywords: ['first period', 'menarche', 'how to know period is coming', 'first time bleeding', 'blood in underwear', 'started my period', 'what do i do first period'],
    response: "🩸 **Menarche: Your First Period!** 🩸\n\nGetting your first period (menarche) is a big milestone! It usually happens between ages 10 and 15, often about 2 years after your breasts start developing.\n\n**Signs it's coming:**\n- You've started getting vaginal discharge (white or clear fluid in your underwear) for the last 6-12 months.\n- You might feel moody, bloated, or have mild cramps in your lower belly.\n\n**What it looks like:**\n- It might not look like red blood right away! It can be brown, pink, or just a few spots in your underwear.\n- Your first few periods might be very light and very irregular (you might get one, and then not get another one for 3 months. That's completely normal!).\n\n**What to do:**\n- **Tell a trusted adult**: Tell your mom, an older sister, an aunt, or the school nurse. They will help you get supplies.\n- **Pack a \"Period Kit\" for school**: Keep a small makeup bag in your backpack with 2 pads, a clean pair of underwear, and a small plastic bag (in case you need to put stained underwear in it). You'll be ready and confident!"
  },
  {
    id: 'skipping_periods_birth_control',
    keywords: ['skip period', 'stop period', 'continuous birth control', 'skipping placebo pills', 'is it safe to skip period', 'no period on pill'],
    response: "🔄 **Is it Safe to Skip Your Period with Birth Control?** 🔄\n\n**Yes! It is completely safe and medically acceptable to skip your period using continuous birth control.**\n\n**How it works:**\nWhen you are on combined hormonal birth control (the pill, the patch, or the ring), the \"period\" you get during your week off isn't a real biological period. It is a \"withdrawal bleed\" caused by the sudden drop in hormones. There is no medical requirement to have this bleed.\n\n**How to do it:**\n- **The Pill**: Skip the placebo row (the sugar pills at the end of the pack) and immediately start a new pack the next day.\n- **The Ring**: Leave the ring in for 3 or 4 weeks, take it out, and immediately insert a new one the same day.\n\n**Why do it?**\nIt is an amazing option for people who suffer from severe cramps (dysmenorrhea), endometriosis, heavy bleeding, PMDD, or who simply don't want to bleed while traveling. \n\n*Note: You might experience some random \"breakthrough spotting\" for the first few months as your body adjusts. Always consult your doctor for personalized advice.*"
  },
  {
    id: 'myth_virginity_hymen',
    keywords: ['hymen', 'virginity test', 'hymen break', 'bleed first time', 'popping cherry', 'hymen torn', 'virgins bleed', 'lose virginity'],
    response: "❌ **Myth vs. Reality: Virginity & The Hymen** ❌\n\n**The Myth**: The hymen is a seal that covers the vagina and \"breaks\" or \"pops\" the first time you have sex, causing you to bleed. If you don't bleed, you aren't a virgin.\n\n**The Reality**:\n- The hymen is just a thin, stretchy, scrunchie-like piece of tissue at the opening of the vagina. It does NOT seal it shut (otherwise period blood couldn't get out!).\n- It naturally stretches, wears down, and changes shape over time from everyday activities like sports, riding a bike, using a tampon, or just growing up.\n- **Most people do NOT bleed the first time they have sex.** If bleeding occurs, it is often due to a lack of lubrication or being tense, not because a seal was \"broken.\"\n- **A doctor cannot tell if you are a virgin by looking at your hymen.** Virginity is a social concept, not a medical condition."
  },
  {
    id: 'myth_pregnancy_period',
    keywords: ['pregnant on period', 'sex during period pregnant', 'can i get pregnant while bleeding', 'period sex pregnancy', 'safe days'],
    response: "❌ **Myth vs. Reality: Pregnancy During Your Period** ❌\n\n**The Myth**: You absolutely cannot get pregnant if you have unprotected sex while on your period.\n\n**The Reality**:\n- **You CAN get pregnant from having sex on your period!**\n- Here's why: Sperm can live inside the female reproductive tract for up to **5 days**. \n- If you have a short menstrual cycle (e.g., 21 or 22 days), you might ovulate (release an egg) just a few days after your period ends.\n- If you have unprotected sex on the last day of your period, the sperm could still be alive inside you 4 or 5 days later when you ovulate, resulting in pregnancy.\n- **Always use protection** if you are trying to avoid pregnancy, regardless of where you are in your cycle!"
  },
  {
    id: 'myth_pregnancy_swimming_pullout',
    keywords: ['pregnant swimming pool', 'pregnant hot tub', 'pregnant from pre-cum', 'pregnant pull out', 'withdrawal myth', 'pregnant from toilet seat'],
    response: "❌ **Myth vs. Reality: How Pregnancy Actually Happens** ❌\n\n**The Myth**: You can get pregnant from swimming in a pool with a boy, sitting on a toilet seat, or from pre-cum if he pulls out in time.\n\n**The Reality**:\n- **Swimming Pools & Hot Tubs**: You **cannot** get pregnant from swimming in a pool, hot tub, or bath where someone has ejaculated. Sperm cannot survive in chlorinated or hot water, and they cannot swim through water, through your swimsuit, and into your vagina.\n- **Toilet Seats**: You **cannot** get pregnant (or get an STI) from sitting on a toilet seat. Sperm die almost immediately when exposed to air and dry surfaces.\n- **Pre-Cum & Pulling Out**: You **CAN** get pregnant from pre-cum (the clear fluid that leaks out of the penis before ejaculation). Pre-cum often contains active, healthy sperm left over in the urethra. The pull-out method is very risky for this exact reason."
  },
  {
    id: 'myth_peeing_after_sex_pregnancy',
    keywords: ['pee after sex prevent pregnancy', 'wash out sperm', 'douching prevent pregnancy', 'shower prevent pregnancy', 'peeing washes sperm'],
    response: "❌ **Myth vs. Reality: Peeing/Washing After Sex** ❌\n\n**The Myth**: If you pee, shower, or wash the vagina out immediately after sex, it washes the sperm away and prevents pregnancy.\n\n**The Reality**:\n- **Peeing does NOT prevent pregnancy.** Urine comes out of the urethra, which is a completely separate hole from the vagina. Peeing after sex is highly recommended, but only because it flushes out bacteria and prevents Urinary Tract Infections (UTIs).\n- **Washing or Douching does NOT prevent pregnancy.** Sperm swim incredibly fast. By the time you get up to wash or douche, millions of sperm are already safely inside the cervix where water cannot reach them. (Plus, douching is dangerous and causes infections!)."
  },
  {
    id: 'myth_birth_control_infertility',
    keywords: ['pill makes you infertile', 'birth control causes infertility', 'iud ruins fertility', 'hard to get pregnant after pill', 'taking a break from pill'],
    response: "❌ **Myth vs. Reality: Birth Control & Infertility** ❌\n\n**The Myth**: Using hormonal birth control (like the pill, implant, or IUD) for many years will \"ruin\" your fertility or make it hard to get pregnant later in life. You need to take \"breaks\" to clean your system out.\n\n**The Reality**:\n- **Birth control does NOT cause infertility.** \n- As soon as you stop taking the pill, removing the ring/patch, or taking out the IUD/implant, the hormones leave your body within a few days. \n- You can literally get pregnant the very next day. \n- The only exception is the Depo-Provera shot, which can sometimes delay the return of fertility for 6 to 10 months, but it does not cause permanent infertility.\n- **You do not need to take \"breaks\" from birth control.** It is perfectly healthy to be on it continuously for decades."
  },
  {
    id: 'myth_home_remedies_infections',
    keywords: ['garlic in vagina', 'yogurt for yeast infection', 'tea tree oil vagina', 'home remedies bv', 'home cure yeast infection', 'cure sti at home'],
    response: "❌ **Myth vs. Reality: Home Remedies for Vaginal Infections** ❌\n\n**The Myth**: You can cure a yeast infection or Bacterial Vaginosis (BV) by putting a clove of garlic, yogurt, or tea tree oil inside your vagina.\n\n**The Reality**:\n- **Do NOT put food in your vagina!**\n- While eating yogurt with live cultures is good for your gut, putting sugary, dairy yogurt inside your vagina can actually feed the bad bacteria and make an infection much worse.\n- Garlic can cause severe chemical burns to the delicate skin of the vagina and can get stuck, requiring a doctor to surgically remove it.\n- Tea tree oil is highly caustic and will cause severe burning and irritation.\n- **The Cure**: Yeast infections require over-the-counter anti-fungal creams (like Monistat) or a pill from a doctor. BV and STIs require prescription antibiotics. Skip the kitchen remedies and see a professional!"
  },
  {
    id: 'puberty_late_early_bloomers',
    keywords: ['late bloomer', 'early bloomer', 'no breasts yet', 'no period yet', 'delayed puberty', 'too small', 'not growing', 'precocious puberty'],
    response: "⏱️ **Puberty Timelines: Early & Late Bloomers** ⏱️\n\nEveryone's \"puberty clock\" is completely unique and mostly determined by genetics (how your parents grew!).\n\n**Late Bloomers (Delayed Puberty):**\n- It is very common to not see major changes until 14 or 15. \n- For girls: If you haven't started developing breasts by 13, or haven't had a period by 15 (or within 3 years of breasts starting to grow), you should visit a doctor just to check your hormone levels.\n- For boys: If you haven't noticed any testicular growth by age 14, a quick doctor's visit is a good idea.\n- Most of the time, late bloomers are perfectly healthy and just need a little more time to catch up!\n\n**Early Bloomers (Precocious Puberty):**\n- Sometimes, puberty starts very early (before age 8 in girls, or before age 9 in boys). \n- This can be confusing and emotionally difficult because your body looks older than you feel. \n- Doctors can sometimes provide medication to pause early puberty if it's happening too fast, allowing your bones and mind to catch up."
  },
  {
    id: 'adolescent_emotions_mood',
    keywords: ['mood swings', 'always angry', 'crying for no reason', 'hating parents', 'emotional', 'hormones crazy', 'teenage angst', 'feeling depressed'],
    response: "🧠 **The Emotional Rollercoaster of Puberty** 🧠\n\nPuberty doesn't just change your body; it physically rewires your brain! \n\n**Why do I feel so crazy?**\n- Your body is being flooded with massive new doses of hormones (estrogen and testosterone) that your brain isn't used to.\n- The \"emotional center\" of your brain (the amygdala) develops much faster than the \"logical/decision-making center\" (the prefrontal cortex). This means you feel emotions intensely, but might struggle to control your reactions to them.\n\n**Common Emotional Changes:**\n- Intense, sudden mood swings (feeling euphoric one minute, and furious or crying the next).\n- Wanting much more independence and privacy from your parents.\n- Caring intensely about what your friends/peers think of you.\n\n**How to cope:**\n- Know that these feelings are 100% normal. \n- Talk to a friend, keep a journal, or listen to music to process the feelings.\n- *Warning sign*: If you feel deeply sad, hopeless, or want to hurt yourself for more than two weeks, this isn't just \"puberty.\" Please reach out to our counselors or a trusted adult—you deserve support."
  },
  {
    id: 'puberty_acne_skin',
    keywords: ['acne', 'pimples', 'zits', 'breakout', 'oily skin', 'clear skin', 'blackheads', 'face washing', 'body acne', 'bacne'],
    response: "🧼 **Puberty & Your Skin (Acne Guide)** 🧼\n\nAcne is one of the most universal parts of puberty. Almost everyone gets it!\n\n**Why it happens:**\n- Puberty hormones (androgens) make your oil glands grow larger and produce much more oil (sebum). \n- This oil mixes with dead skin cells and clogs your pores. Bacteria then grow in the clogged pore, causing a red, swollen pimple.\n\n**Basic Skincare Rules:**\n1. **Wash twice a day**: Use a gentle, unscented cleanser morning and night. Do not scrub hard—scrubbing makes acne worse by irritating the skin!\n2. **Don't pop them!** Squeezing pimples pushes bacteria deeper into the skin, making the pimple last much longer and causing permanent scars.\n3. **Look for Salicylic Acid or Benzoyl Peroxide**: These are cheap, over-the-counter ingredients that actively fight acne.\n4. **Moisturize**: Even if your skin is oily, use a lightweight, \"non-comedogenic\" (won't clog pores) moisturizer so your skin doesn't overproduce oil.\n\nIf your acne is very painful, deep (cystic), or leaving scars, a dermatologist can prescribe stronger creams or pills to clear it up."
  },
  {
    id: 'puberty_sweat_hygiene',
    keywords: ['sweat', 'sweaty', 'body odor', 'smell bad', 'deodorant', 'antiperspirant', 'stinky', 'showering', 'bo'],
    response: "🚿 **Sweat & Body Odor During Puberty** 🚿\n\nSuddenly noticing that you smell different (or stronger) is a hallmark sign of puberty.\n\n**What's changing?**\n- You actually have two types of sweat glands. During puberty, a new type of gland (apocrine glands) \"wakes up\" in your armpits and groin.\n- The sweat they produce is thicker. When the natural bacteria on your skin mix with this new sweat, it creates Body Odor (B.O.).\n\n**How to manage it:**\n- **Shower Daily**: Especially after sports or sweating. Wash your armpits and groin thoroughly with soap.\n- **Deodorant vs. Antiperspirant**: \n  - *Deodorant* covers up the smell with perfume and makes your skin slightly acidic to deter bacteria.\n  - *Antiperspirant* actually plugs your sweat glands with aluminum so you don't sweat as much. (Both are safe to use!).\n- **Clean Clothes**: Wear clean underwear, socks, and shirts every single day. Sweat gets trapped in fabric and bacteria will grow there."
  },
  {
    id: 'body_image_eating',
    keywords: ['body image', 'feeling fat', 'too skinny', 'hate my body', 'dieting', 'eating disorder', 'anorexia', 'bulimia', 'comparing to models'],
    response: "🪞 **Body Image & Social Media Reality Check** 🪞\n\nDuring puberty, your body is rapidly changing size and shape. It is normal to feel awkward or uncomfortable in your \"new\" body.\n\n**The Social Media Trap:**\n- Remember that 99% of what you see on Instagram, TikTok, and in magazines is edited, filtered, or heavily posed. \n- Comparing your everyday, growing body to an adult influencer's highly-edited highlight reel will always make you feel bad.\n\n**Healthy Body Image Facts:**\n- **Gaining weight during puberty is required.** Your body needs extra fat to trigger hormones, grow taller, and develop reproductive organs (like breasts and hips). \n- Extreme dieting, starving yourself, or forcing yourself to throw up (eating disorders) are incredibly dangerous and can cause your heart to fail or permanently stop your growth.\n- Focus on what your body can *do* (run, dance, hug, paint, play sports) rather than just what it *looks* like.\n\nIf you find yourself obsessing over food, calories, or your weight to the point where it makes you miserable, please talk to our clinical team or a counselor. We are here to help."
  },
  {
    id: 'puberty_voice_cracking',
    keywords: ['voice cracking', 'voice getting deeper', 'adams apple', 'why is my voice squeaky', 'voice changing', 'deep voice'],
    response: "🗣️ **Voice Changes & Cracking** 🗣️\n\nDuring puberty, almost everyone's voice drops and gets deeper, but it is especially noticeable in boys.\n\n**Why it happens:**\n- Testosterone causes the larynx (voice box) to grow much larger and thicker.\n- As it grows, it tilts outward at the front of your throat, which forms the bump known as the **Adam's Apple**.\n- Because your vocal cords are suddenly longer and thicker, your voice drops to a lower pitch.\n\n**The Cracking:**\n- While your larynx is growing, your body is still figuring out how to control these new, larger vocal cords.\n- This causes your voice to suddenly \"crack\" or squeak when you are talking.\n- It is entirely normal, and everyone goes through it! It usually stops once your larynx finishes growing in a year or two."
  },
  {
    id: 'puberty_body_hair',
    keywords: ['pubic hair', 'armpit hair', 'leg hair', 'shaving', 'mustache', 'facial hair', 'how to shave', 'trimming hair', 'ingrown hairs'],
    response: "🪒 **Body Hair & Shaving 101** 🪒\n\nOne of the most obvious signs of puberty is growing hair in new places: the pubic area (around the genitals), armpits, legs, face, and sometimes chest or back.\n\n**To Shave or Not to Shave?**\n- Removing body hair is a **100% personal choice**. There is absolutely no medical or hygiene reason to shave your armpits, legs, or pubic hair. It is entirely up to what makes you comfortable!\n\n**Safe Shaving Rules:**\n1. **Never dry shave**: Always shave in the shower when hair is soft. Use shaving cream or a gentle soap.\n2. **Use a sharp, clean razor**: Dull blades cause severe irritation and razor bumps.\n3. **Shave WITH the grain**: Shave in the direction the hair grows, not against it. Shaving against it causes painful ingrown hairs (especially in the pubic area!).\n4. **Moisturize**: Put unscented lotion on after shaving to soothe the skin.\n\n*Note for Facial Hair*: For boys, facial hair usually starts as a thin \"peach fuzz\" mustache before slowly turning into thicker hair on the chin and cheeks."
  },
  {
    id: 'puberty_wet_dreams',
    keywords: ['wet dream', 'wet dreams', 'nocturnal emission', 'woke up sticky', 'cum in sleep', 'woke up with cum', 'ejaculate in sleep'],
    response: "💤 **Wet Dreams (Nocturnal Emissions)** 💤\n\nA \"wet dream\" is when a boy/person with a penis ejaculates (releases semen) while they are asleep. \n\n**The Facts:**\n- **It is completely normal and healthy!** It is a sign that your body is maturing and producing sperm.\n- **You cannot control it.** It happens automatically while you sleep. You don't have to be having a sexual dream for it to happen.\n- **It's not your fault.** You should never feel ashamed or embarrassed.\n- **What to do**: Just wake up, wash your genitals with warm water and soap, put on clean underwear, and throw the dirty underwear or sheets in the laundry.\n\nWet dreams are most common during early puberty and usually happen less frequently as you get older."
  },
  {
    id: 'puberty_growing_pains',
    keywords: ['growing pains', 'legs hurt at night', 'knees hurt growing', 'growth spurt pain', 'bones ache', 'osgood schlatter'],
    response: "🦴 **Growth Spurts & Growing Pains** 🦴\n\nDuring a growth spurt, you can grow several inches in just one year! \n\n**Growing Pains:**\n- Because your bones are growing so incredibly fast, your muscles and tendons have to stretch rapidly to keep up with them.\n- This can cause a dull, aching pain, usually in your legs, knees, calves, or thighs, especially late in the day or at night.\n- It is very common and completely normal.\n\n**How to relieve the pain:**\n- Take a warm bath before bed.\n- Gently massage and stretch your legs.\n- Place a heating pad on the sore muscles.\n- Drink plenty of water and eat foods high in calcium (to help your bones) and potassium (to help your muscles).\n\n*(Note: If the pain is severe, constant, in only one specific joint, or causes you to limp, tell a parent or doctor, as it could be a sports injury or a common growth condition called Osgood-Schlatter disease).* "
  },
  {
    id: 'digital_safety_sexting',
    keywords: ['sexting', 'nudes', 'sending pictures', 'revenge porn', 'blackmail', 'leaked photos', 'asking for nudes', 'digital consent'],
    response: "📱 **Digital Safety & Sexting** 📱\n\nSending intimate messages or photos (sexting) is common, but it comes with huge, permanent risks in the digital age.\n\n**The Reality of Nudes:**\n- Once you hit \"send,\" you permanently lose control of that image. Even if you trust the person now, breakups happen, and people can be cruel.\n- Snapchat screenshots, screen recordings, and hidden cameras are real threats.\n- **The Law**: In many places, if you are under 18 and you send a nude photo of yourself, or if someone forwards it, they can be charged with distributing child pornography. It is a serious crime.\n\n**How to Protect Yourself:**\n- **Never show your face, tattoos, or identifying marks** if you do decide to send something.\n- **You always have the right to say NO.** If someone pressures you, threatens to break up with you, or calls you a prude for not sending photos, that is toxic manipulation, not love.\n- If someone is threatening to leak your photos (blackmail/sextortion), do not pay them or send more photos. Tell a trusted adult or the police immediately."
  },
  {
    id: 'medical_confidentiality_minors',
    keywords: ['doctor without parents', 'will my parents know', 'confidentiality', 'can i get birth control without parents', 'secret sti test', 'teen health rights'],
    response: "🩺 **Your Rights: Medical Confidentiality for Minors** 🩺\n\nMany teenagers are terrified to seek medical help for sexual health because they worry their parents will find out. \n\n**What You Need to Know:**\n- In many countries and states (like Title X clinics in the US), minors have the legal right to receive **STI testing, birth control, and pregnancy care completely confidentially**, without a parent's permission or knowledge.\n- Doctors are legally bound by patient confidentiality. They cannot tell your parents what you discussed *unless* you are in immediate danger of harming yourself or others, or if there is evidence of abuse by an adult.\n\n**How to get help:**\n- Search for local \"Youth Health Clinics,\" \"Planned Parenthood,\" or public health departments.\n- When you arrive, you can explicitly tell the doctor/nurse: \"I need this appointment to remain strictly confidential from my parents.\" They handle this every single day and will protect your privacy."
  },
  {
    id: 'attraction_spectrum_asexuality',
    keywords: ['asexual', 'aromantic', 'dont want sex', 'not attracted to anyone', 'ace', 'aro', 'is it normal to not want sex', 'low sex drive'],
    response: "🖤 **Asexuality & The Attraction Spectrum** 🖤\n\nSociety pushes a narrative that everyone must be obsessed with sex and dating. If you don't feel that way, you are not broken!\n\n**Different Types of Attraction:**\n- **Sexual Attraction**: Wanting to have sexual contact with a specific person.\n- **Romantic Attraction**: Wanting to have a romantic relationship (dating, cuddling, falling in love) with someone. You can have one without the other!\n\n**The Asexual (Ace) Spectrum:**\n- **Asexual**: People who experience little to no sexual attraction to anyone. They might still fall in love romantically, or they might not!\n- **Aromantic (Aro)**: People who experience little to no romantic attraction.\n- **Demisexual**: People who only experience sexual attraction *after* forming a deep emotional bond with someone.\n\nIt is completely normal to be on the \"Ace\" spectrum, or simply to have a lower sex drive than your peers. You never have to force yourself to do something you don't want to do just to \"fit in.\""
  },
  {
    id: 'safe_masturbation_hygiene',
    keywords: ['safe masturbation', 'masturbation hygiene', 'chafing', 'death grip', 'using objects', 'sex toys safe', 'what to use to masturbate'],
    response: "✨ **Safe Masturbation: Hygiene & Habits** ✨\n\nMasturbation is a healthy way to explore pleasure, but doing it safely prevents painful injuries or infections.\n\n**Crucial Safety Rules:**\n1. **Wash your hands & toys**: Always wash your hands before touching your genitals. If you use sex toys, clean them with warm water and antibacterial soap before and after every use.\n2. **Never insert household objects**: Do NOT put random household items (like bottles, vegetables, or hairbrush handles) inside the vagina or anus. They can break, get stuck, or cause severe, life-threatening bacterial infections. Only use toys specifically designed for sexual use.\n3. **Use Lube!**: Friction can cause painful micro-tears and chafing on the penis, clitoris, or vulva. Use water-based personal lubricant. Never use scented lotions or soap as lube.\n4. **Avoid the \"Death Grip\"**: For people with penises, gripping too tightly or using intense speed out of habit can cause \"Death Grip Syndrome,\" making it very difficult to achieve an erection or orgasm with a real partner later on. Try a lighter touch or use lube!"
  },
  {
    id: 'sti_crabs_scabies',
    keywords: ['crabs', 'pubic lice', 'scabies', 'itching groin', 'bugs in pubic hair', 'parasite', 'intense itching'],
    response: "🐛 **Parasitic STIs: Pubic Lice (Crabs) & Scabies** 🐛\n\nNot all STIs are viruses or bacteria—some are tiny bugs!\n\n**Pubic Lice (Crabs):**\n- **What they are**: Tiny insects that live in coarse body hair (mostly pubic hair, but sometimes armpits or eyelashes) and feed on blood.\n- **Transmission**: Close physical contact or sharing towels, clothing, or beds with an infected person. Condoms do NOT protect against them.\n- **Symptoms**: Intense itching in the groin, visible tiny white eggs (nits) attached to hair, or seeing the tiny grey bugs crawling.\n- **Treatment**: Easily cured with over-the-counter lice-killing lotions and by washing all bedding and clothes in very hot water.\n\n**Scabies:**\n- **What they are**: Microscopic mites that burrow under the top layer of your skin to lay eggs.\n- **Symptoms**: A severe, pimple-like rash and itching that gets *much* worse at night.\n- **Treatment**: Requires prescription scabicide creams for your entire body."
  },
  {
    id: 'sti_hepatitis',
    keywords: ['hepatitis b', 'hep b', 'hepatitis c', 'hep c', 'yellow skin', 'jaundice', 'liver sti', 'sharing needles'],
    response: "🦠 **Hepatitis B & C** 🦠\n\nHepatitis is an infection that causes severe inflammation of the liver. While some types come from food, Hep B and C are often transmitted sexually or through blood.\n\n**Hepatitis B (Hep B):**\n- **Transmission**: Highly contagious through semen, vaginal fluids, and blood. Even sharing a toothbrush or razor with an infected person can pass it!\n- **Symptoms**: Often asymptomatic, but can cause jaundice (yellowing of skin/eyes), dark urine, extreme fatigue, and stomach pain.\n- **Prevention**: There is a highly effective vaccine for Hepatitis B! You probably got it as a baby, but if not, you can get it now.\n\n**Hepatitis C (Hep C):**\n- **Transmission**: Mostly spread through blood (sharing needles for tattoos, piercings, or drugs), but can be sexually transmitted, especially during rough sex or anal sex.\n- **Treatment**: There is no vaccine, but modern medicine can completely *cure* Hep C with pills in 8-12 weeks if caught before the liver is permanently damaged."
  },
  {
    id: 'sti_pid_consequences',
    keywords: ['pid', 'pelvic inflammatory disease', 'untreated sti', 'untreated chlamydia', 'infertility sti', 'painful lower belly'],
    response: "🚨 **The Danger of Ignored STIs: Pelvic Inflammatory Disease (PID)** 🚨\n\nBecause many STIs (like Chlamydia and Gonorrhea) have zero symptoms, people often ignore them for months or years. In people with a uterus, this leads to PID.\n\n**What is PID?**\n- The bacteria travel from the vagina, up through the cervix, and permanently infect the uterus, fallopian tubes, and ovaries.\n\n**Symptoms:**\n- Severe, deep pain in the lower belly.\n- Painful periods or pain deep inside during sex.\n- High fever or unusual discharge.\n\n**The Long-Term Damage:**\n- PID creates thick scar tissue inside the delicate fallopian tubes.\n- This scar tissue can make it **impossible to get pregnant naturally later in life (infertility)**.\n- It also highly increases the risk of an Ectopic Pregnancy (where an egg gets stuck in the scarred tube and bursts, which is a life-threatening emergency).\n\n*This is why you must get tested every year, even if you feel perfectly healthy!*"
  },
  {
    id: 'sti_testing_what_happens',
    keywords: ['what happens at an sti test', 'how do they test for stis', 'do sti tests hurt', 'blood test sti', 'urine test sti', 'swab test sti', 'std clinic'],
    response: "🩺 **Getting Tested: What Actually Happens?** 🩺\n\nGetting an STI test is fast, easy, and usually completely painless. You don't have to be scared!\n\n**Here is how they test for different things:**\n\n1. **The Urine Test (Peeing in a cup):**\n   - Checks for: Chlamydia and Gonorrhea.\n   - *Tip*: Don't pee for at least an hour before the test to ensure the bacteria are concentrated in the sample.\n\n2. **The Blood Test (A quick finger prick or blood draw):**\n   - Checks for: HIV, Syphilis, Hepatitis, and sometimes Herpes.\n\n3. **The Swab Test (A q-tip gently rolled on the area):**\n   - If you have an active sore or unusual discharge, they will gently swab the throat, anus, vagina, or the sore itself.\n   - Checks for: Herpes, HPV, Trichomoniasis, or throat/anal Gonorrhea.\n\nThere is no giant needle or painful procedure. It usually takes 10 minutes total!"
  },
  {
    id: 'sti_telling_a_partner',
    keywords: ['how to tell partner i have an sti', 'telling someone i have herpes', 'i tested positive', 'sti communication', 'my partner gave me an sti'],
    response: "🗣️ **Communication: Telling a Partner You Have an STI** 🗣️\n\nIf you test positive for an STI, telling a current or past partner can feel terrifying, but it is the most responsible, mature, and caring thing you can do.\n\n**How to do it:**\n- **Do it quickly**: Don't put it off. They need to get treated before it damages their body or they pass it to someone else.\n- **Be direct and factual**: \"Hey, I just got my test results back and I tested positive for Chlamydia. You should get tested and treated as soon as possible.\"\n- **Remove the blame game**: STIs happen. Trying to figure out \"who gave it to who\" usually just leads to angry fights and doesn't solve the medical problem. Focus on getting both of you healthy.\n- **If you have a chronic STI (like Herpes or HIV)**: Tell new partners *before* you are intimate. Say, \"I want to be upfront because I respect you: I carry the virus that causes cold sores/herpes. I take medication to prevent it, but I wanted you to know so we can be safe.\"\n\n*If you are too afraid of an abusive or angry partner, many health clinics offer an anonymous notification service where they will text your partner for you without revealing your name.*"
  },
  {
    id: 'sti_chancroid',
    keywords: ['chancroid', 'painful sore genitals', 'bleeding sore', 'ulcer genitals', 'swollen groin nodes'],
    response: "🦠 **Chancroid** 🦠\n\nChancroid is a bacterial STI that causes painful open sores on the genitals.\n\n**Symptoms:**\n- Begins as a small bump that quickly turns into a shallow, very painful ulcer or sore (unlike the sore in Syphilis, which is painless).\n- The sore often bleeds or leaks fluid if touched.\n- Swollen, painful lymph nodes in the groin.\n\n**Treatment:**\n- Easily cured with antibiotics (like Azithromycin or Ceftriaxone).\n- If left untreated, the sore makes it extremely easy for HIV to enter the body."
  },
  {
    id: 'sti_molluscum',
    keywords: ['molluscum contagiosum', 'small bumps genitals', 'pearly bumps', 'dimpled bumps', 'water warts'],
    response: "🦠 **Molluscum Contagiosum** 🦠\n\nMolluscum is a viral skin infection that causes small, firm, dome-shaped bumps with a tiny dimple in the center.\n\n**Transmission:**\n- Spread through skin-to-skin contact, sharing towels, or during sexual intimacy.\n- Condoms do not fully protect against it since it lives on the surrounding skin.\n\n**Treatment:**\n- In healthy people, it goes away entirely on its own within 6 to 12 months.\n- Doctors can freeze the bumps off or prescribe creams to speed up the process if they are bothersome or spreading."
  },
  {
    id: 'sti_lgv_donovanosis',
    keywords: ['lgv', 'lymphogranuloma venereum', 'granuloma inguinale', 'donovanosis', 'flesh eating sti', 'severe groin swelling'],
    response: "🦠 **Rare STIs: LGV & Donovanosis** 🦠\n\nWhile rare in many Western countries, these STIs occur globally and are very serious.\n\n**LGV (Lymphogranuloma Venereum):**\n- Caused by a specific, aggressive strain of Chlamydia.\n- Causes a small, painless sore followed by extreme, painful swelling of the lymph nodes in the groin, which can burst and drain pus. Common in populations having unprotected anal sex.\n- Treated with 3 weeks of antibiotics.\n\n**Donovanosis (Granuloma Inguinale):**\n- A bacterial STI that causes large, painless, beefy-red sores on the genitals.\n- Often called a \"flesh-eating\" STI because if left untreated, the sores slowly destroy the surrounding tissue.\n- Completely curable with long courses of antibiotics."
  },
  {
    id: 'sti_cmv_cytomegalovirus',
    keywords: ['cmv', 'cytomegalovirus', 'kissing disease sti', 'mono sti'],
    response: "🦠 **CMV (Cytomegalovirus)** 🦠\n\nCMV is a very common virus related to the herpes and mono viruses.\n\n**Transmission:**\n- Spread through bodily fluids: saliva, semen, vaginal fluids, blood, and breast milk.\n- Over half of all adults have had it, often without ever knowing it.\n\n**Why it matters:**\n- In healthy teenagers, it causes mild flu-like symptoms or mono-like symptoms, then stays dormant in the body forever.\n- However, it is extremely dangerous if passed to a pregnant person who has never had it before, as it can cause severe birth defects (like hearing loss) in the baby. "
  },
  {
    id: 'sti_ureaplasma',
    keywords: ['ureaplasma', 'urethritis', 'burning pee no sti', 'weird discharge no sti'],
    response: "🦠 **Ureaplasma** 🦠\n\nUreaplasma is a tiny bacterium that naturally lives in the urinary or genital tract of many healthy people without causing issues. \n\n**When it becomes a problem:**\n- If the bacteria overgrow, they can cause inflammation.\n- **Symptoms**: Burning during urination, unusual discharge, or pelvic pain. (Very similar to Chlamydia symptoms!).\n- Because it is technically part of the normal flora, doctors don't always test for it unless you have symptoms that aren't cured by standard STI treatments.\n- Easily treated with specific antibiotics."
  },
  {
    id: 'deep_dive_bacterial_vaginosis',
    keywords: ['bv', 'bacterial vaginosis', 'fishy smell vagina', 'fishy odor', 'grey discharge', 'gardnerella', 'is bv an sti'],
    response: "🦠 **Deep Dive: Bacterial Vaginosis (BV)** 🦠\n\nBV is the most common vaginal infection in women ages 15-44. \n\n**Is it an STI?**\n- **No.** You cannot \"catch\" BV from a toilet seat or a pool, and it is not considered an STI. \n- However, having a new sexual partner, having multiple partners, or douching throws off the natural pH balance, allowing the bad bacteria (like *Gardnerella*) to overgrow.\n\n**Symptoms:**\n- A strong, very distinct \"fishy\" odor, especially right after sex or during your period.\n- Thin, watery, greyish-white discharge.\n- Mild burning or itching.\n\n**Treatment:**\n- It requires prescription antibiotics (pills or vaginal gel) from a doctor. Home remedies do not work and often make it worse."
  },
  {
    id: 'deep_dive_yeast_infection',
    keywords: ['yeast infection', 'candidiasis', 'candida', 'cottage cheese discharge', 'extreme vaginal itching', 'thrush', 'burning vagina'],
    response: "🦠 **Deep Dive: Yeast Infections (Candidiasis)** 🦠\n\nA yeast infection is a fungal infection. A small amount of yeast naturally lives in the vagina, but when it overgrows, it causes misery!\n\n**Causes:**\n- Taking antibiotics (which kills the good bacteria that keep yeast in check).\n- Wearing tight, wet clothes (like sitting in a wet swimsuit) because yeast loves warm, moist environments.\n- High blood sugar or diabetes.\n\n**Symptoms:**\n- **Intense, maddening itching** of the vulva and vagina.\n- Red, swollen, sore labia.\n- Thick, white, clumpy discharge that looks exactly like cottage cheese (but usually has no smell).\n\n**Treatment:**\n- You can buy anti-fungal creams (like Monistat) over the counter at any pharmacy. If it's your first time having one, see a doctor to confirm it isn't something else."
  }
];
